# Generated by Django 4.0.4 on 2022-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_author_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='released_year',
            field=models.IntegerField(verbose_name='Released year'),
        ),
    ]
